# Before starting this docker-compose make sure to run the docker-compose-tool.yaml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vi-search-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - vi-app-network
networks:
  vi-app-network:
    name: vi-app-network
    driver: bridge
