version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vi-search-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    #environment:  <!--ignore for now-->
      #- SPRING_REDIS_HOST=redis
      #- SPRING_REDIS_PORT=6379
